language: go

go:
    - 1.7
    - 1.8
    - 1.9
    - tip
compiler:
    - g++
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install tesseract-ocr=3.05
    - sudo apt-get install libtesseract-dev
    - sudo apt-get install libleptonica-dev
before_script:
    - go get github.com/otiai10/mint
script:
    - go test -v
