name: Runtime Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [main, develop]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    name: macOS Go${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install tesseract
        run: brew install tesseract
      - name: Install pkg
        run: go get -u -v -t ./...
      - name: Test
        run: go test -v -cover ./...
      - name: Coverage
        run: go test -v -cover -race -coverprofile=coverage -covermode=atomic
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage
          verbose: true
  docker-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - ubuntu
          - alpine
          - archlinux
          - centos
          - debian
          - fedora
          - mingw
          - quickstart
    name: Docker ${{ matrix.runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        shell: 'script -q -e -c "bash {0}"'
        run: bash ./test/runtime --driver docker --build --run ${{ matrix.runtime }}

  vagrant-test:
    runs-on: macos-10.15
    strategy:
      matrix:
        runtime:
          - freebsd
    name: Vagrant ${{ matrix.runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        run: bash ./test/runtime --driver vagrant --build --run ${{ matrix.runtime }}
