name: Vagrant Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  vagrant-test:
    runs-on: macos-latest
    strategy:
      matrix:
        runtime:
          - freebsd
    name: Vagrant ${{ matrix.runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        run: bash ./test/runtime --driver vagrant --build --run ${{ matrix.runtime }}
